language: node_js
node_js:
  - "7"
install:
  - npm install
env:
  - NODE_ENV=production
  - NPM_CONFIG_PRODUCTION=true
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API_KEY}
  app: bbt-web-new