language: node_js
node_js:
  - "7"
install:
  - npm install
env:
  - NODE_ENV=heroku
script: npm run build
before_deploy:
  - cd ./dist
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ${HEROKU_API_KEY}
  app: bbt-web-new